// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://jdwwmoyczlmreayzjidp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impkd3dtb3ljemxtcmVheXpqaWRwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ1MjMzNzgsImV4cCI6MjA4MDA5OTM3OH0.Wey0Ov0j87RNnq0t4E4x5aiXgxy5_Gx2mqGB6gtfhzY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);